Css two column layout
silva-tim/c0523-code-solutions pull request #41
Opened 2023-05-18 21:18 UTC by silva-tim

<img width="1436" alt="Screen Shot 2023-05-18 at 2 18 31 PM" src="https://github.com/silva-tim/c0523-code-solutions/assets/114685872/d1ff90a1-5f0a-4764-9ee2-ff9dcd9c3901">

2023-05-19 19:24 UTC, shawnkost requested changes
Missing a few `alt` attributes here!

2023-05-19 19:24 UTC, shawnkost commented on css-two-column-layout/index.html
> +              <img src="images/software.svg" />
Missing `alt` attribute

2023-05-19 19:24 UTC, shawnkost commented on css-two-column-layout/index.html
> +              <img src="images/practice.svg" />
Missing `alt` attribute

2023-05-19 19:24 UTC, shawnkost commented on css-two-column-layout/index.html
> +              <img src="images/circumstance.svg" />
Missing `alt` attribute

2023-05-19 19:24 UTC, shawnkost commented on css-two-column-layout/index.html
> +              <img src="images/data.svg" />
Missing `alt` attribute

2023-05-22 15:46 UTC, silva-tim commented on css-two-column-layout/index.html
> +              <img src="images/data.svg" />
Added alt tags

2023-05-23 16:50 UTC, shawnkost approved these changes
👍🏻

2023-05-23 21:49 UTC, merged