react-search-component - Tim Silva
silva-tim/c0523-code-solutions pull request #99
Opened 2023-06-29 17:15 UTC by silva-tim

![Recording 2023-06-29 at 10 14 47](https://github.com/silva-tim/c0523-code-solutions/assets/114685872/501a1a6a-2d25-45c8-810d-e5f162af2c5e)

2023-06-29 21:29 UTC, TimelikeClosure requested changes
@silva-tim Please make sure the search bar has a magnifying glass button, as in the mockup.

2023-07-06 16:32 UTC, RobertGardner approved these changes
Good. Some suggestions.

2023-07-06 16:32 UTC, RobertGardner commented on react-search-component/my-app/src/SearchableList.jsx
> +  const [value, setValue] = useState('');
"value" isn't a very descriptive name. It would be best to use a name that describes what state this value holds, like "searchTerm" or "filter".

2023-07-06 16:32 UTC, RobertGardner commented on react-search-component/my-app/src/SearchableList.jsx
> +  }
You could more easily create `currentRender` using `list.filter` plus `list.map`.

2023-07-06 16:32 UTC, RobertGardner commented on react-search-component/my-app/src/SearchableList.jsx
> +  let currentRender = [...list];
You initialize `currentRender` here, but then you reassign it in both branches of the `if` statement below. So this initialization is a waste. You could just use `let currentRender;`.

2023-07-06 16:32 UTC, RobertGardner commented on react-search-component/my-app/src/SearchableList.jsx
> +  return <input value={value} onChange={onCustomChange} type="search"></input>;
Since there is no content in the `input` tag, make it self-closing.

2023-07-06 16:42 UTC, merged